out_path: s3://thetradedesk-mlplatform-us-east-1/data/prod/audience/scores/tdid2seedid/v=1/date={{
  run_date.strftime('%Y%m%d') }}/
population_score_path: s3://thetradedesk-mlplatform-us-east-1/data/prod/audience/scores/seedpopulationscore/v=1/date={{
  run_date.strftime('%Y%m%d') }}/
