rsmV2FeatureDestPath: s3a://thetradedesk-mlplatform-us-east-1/configdata/prod/audience/schema/RSMV2/v=1/{{
  run_date.strftime('%Y%m%d') }}/features.json
optInSeedEmptyTagPath: s3a://thetradedesk-mlplatform-us-east-1/data/prod/audience/RSMV2/Seed_None/v=1/{{
  run_date.strftime('%Y%m%d') }}/_Full_EMPTY
